project:
  type: website
  output-dir: docs
  resources:
    - slow-blink.mp4
website:
  title: "Chemometrics and Spectroscopy Using R"
  site-url: http://chemospec.org
  description: "Applying chemometrics to spectroscopy using R"
  cookie-consent:
    prefs-text: "Cookies are used to track visits only"
  body-footer: <script data-goatcounter="https://chemospec.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  margin-header: subscribe.html
  comments:
    utterances:
      repo: bryanhanson/CSR
  navbar:
    background: primary
    foreground: "#FFFFFF"
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "R-Bloggers"
        href: https://www.r-bloggers.com/
      - icon: envelope-fill
        href: mailto:hanson@depauw.edu
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/profbryanhanson.bsky.social
      - icon: git
        href: https://github.com/bryanhanson
      - icon: rss
        file: index.xml
format:
  html:
    theme: simplex
    css: styles.css
    code-line-numbers: true
