---
date: "2021-11-21"
title: The Back Story
comments: false
---

# About This Blog

> "Open source means everyone can see my stupid mistakes.
> Version control means everyone can see every stupid mistake I’ve ever made."
>
> -- <cite>Karl Broman</cite>

The purpose of this blog is to provide a place to share my work in the area of Chemometrics & Spectroscopy using FOSS (free and open source) tools.  Mostly I work with `R` but I use other tools as needed.  Some areas I expect to write about from time-to-time include:

* Major updates to `R` packages I author [See here](https://github.com/bryanhanson?tab=repositories)
* Tutorials on how to accomplish certain tasks, generally inspired by user questions.
* Developments in the chemometrics and spectroscopy community.
* Occasionally, discussion of interesting papers.

# About Your Host

You can reach me at <a href="mailto:hanson@depauw.edu">hanson@depauw.edu</a>.  Occasionally I am on [Twitter](https://twitter.com/profbryanhanson).

### Now

I am currently a freelance `R` consultant with expertise in:

* Development of `R` packages supporting science, especially spectroscopy and chemometrics
* Spectroscopy (NMR, IR, UV-Vis etc)
* Chemometrics
* Exploratory Data Analysis
* Data Visualizations
* Data Management: organization, cleaning
* Reproducible Research: the automated writing of research reports
* `R` Training
* Web page creation and maintenance
* Familiar with `R`, markdown, LaTeX, html, css, JavaScript
* [Resume](resume.html)

### Then

I retired in June 2018 from DePauw University after 32 years of teaching chemistry and biochemistry.  It was a good run. No regrets.  Just time to do something else.

<hr>

[Karl Broman quote source](https://kbroman.wordpress.com/2011/08/17/the-stupidest-r-code-ever/)
