baseurl = "/"
languageCode = "en-us"
copyright = "Creative Commons Attribution-ShareAlike 4.0 International License"
title = "Chemometrics & Spectroscopy using R"
theme = "hugo-lithium"
googleAnalytics = "UA-25299003-2"
disqusShortname = "chemospec"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    tags = "/tags/:slug/"

[author]
    name = "Bryan A. Hanson"
    
[taxonomies]
    tag = "tags"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Links"
    url = "/links/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "BlogBanner.png"
    width = 720
    height = 120
    alt = "Chemometrics & Spectroscopy using R"
