---
title: "Bryan A. Hanson"
date: "2021-11-21"
disable_comments: true
---

*This is a summary of my professional experience related to software development projects.  In prior times I taught chemistry and biochemistry for 32 years at [DePauw University](https://depauw.edu). If you would like a more traditional CV covering that phase, please click [here](Hanson_CV_Thru_2018.pdf).*

Expertise in:

* Development of R packages supporting science, especially spectroscopy and chemometrics (12 + years).
* Exploratory data analysis and visualization.
* Reproducible research and report automation.
* Web page creation and maintenance.
* Comfortable with R, markdown, LaTeX, html, css, JavaScript.

## Positions Held

<table>
  <tr>
    <td>Professor of Chemistry & Biochemistry, DePauw University</td>
    <td>&nbsp;&nbsp;&nbsp;</td>
    <td>1986--2018</td>
  </tr>
</table>

## Education

<table>
  <tr>
    <td>Post-doctoral Associate, Oregon State University</td>
    <td>&nbsp;&nbsp;&nbsp;</td>
    <td>1984--1986</td>
  </tr>
	<tr>
    <td>Ph.D., Chemistry, University of California Los Angeles, California</td>
    <td>&nbsp;&nbsp;&nbsp;</td>
    <td>September 1984</td>
  </tr>
	<tr>
    <td>B.S., Biochemistry, California State University Los Angeles, California</td>
    <td>&nbsp;&nbsp;&nbsp;</td>
    <td>October 1981</td>
  </tr>
</table>

## R Software Packages Authored

All my work can be seen at [Github](https://github.com/bryanhanson?tab=repositories). Here are some highlights:

[ChemoSpec](https://CRAN.R-project.org/package=ChemoSpec): Exploratory Chemometrics for Spectroscopy

[ChemoSpec2D](https://CRAN.R-project.org/package=ChemoSpec2D): Exploratory Chemometrics for 2D Spectroscopy

[exCon](https://CRAN.R-project.org/package=exCon): Interactive Exploration of Contour Data [live demo](https://bryanhanson.github.io/exCon/exCon.html)

[readJDX](https://CRAN.R-project.org/package=readJDX): Import Data in the JCAMP-DX Format

[SpecHelpers](https://CRAN.R-project.org/package=SpecHelpers): Spectroscopy Related Utilities

[unmixR](https://gitlab.com/chemometrics/unmixR): Hyperspectral Unmixing with R, with Anton Belov, Conor McManus, Claudia Beleites and Simon Fuller

[HiveR](https://CRAN.R-project.org/package=HiveR): Hive Plots in 2D and 3D

[LindenmayeR](https://CRAN.R-project.org/package=HiveR): Functions to Explore L-Systems (Lindenmayer Systems)

## Selected Presentations

"Development of Chemometric Tools for 2D NMR Data Sets" Poster at PANIC 2018 (Practical Applications of NMR in Industry Conference), La Jolla (San Diego) California, March 2018. [Download](documents/Panic_2018_Poster.pdf)

"Using R to Make Sense of NMR Data Sets" invited talk at PANIC 2017 (Practical Applications of NMR in Industry Conference), Hilton Head South Carolina, February 2017. [Download](documents/Panic_2017_Presentation.pdf)

"unmixR: Hyperspectral Unmixing in \emph{R}" with Conor McManus, Simon Fuller, and Claudia Beleites.  Poster at \emph{useR!} 2014,  University of California at Los Angeles, June 30--July 3, 2014. [Download](documents/useR_2014_Poster.pdf)

"Preliminary Metabolic Investigation of Saline-Stressed *Portulac olercea* using 1H NMR" with Paulina J. Haight and John S. Harwood.  Poster at the ACS National Meeting, Indianpolis, September 2013. [Download](documents/ACS_2013_Poster.pdf)

"HiveR: 2 and 3D Hive Plots of Networks" Invited talk at useR! 2012 Conference, Nashville Tennessee, June 12--15, 2012. [Download](documents/useR_2012_Presentation.pdf)

"HiveR: 2 and 3D Hive Plots of Networks" Poster at useR! 2012 Conference, Nashville Tennessee, June 12--15, 2012. [Download](documents/useR_2012_Poster.pdf)

"Implementation of ANOVA-PCA in R for Multivariate Exploration" with M. J. Keinsley.  Poster at useR! 2012 Conference, Nashville Tennessee, June 12--15, 2012. [Download](documents/useR_2012_Poster2.pdf)

"The Effect of Climate Change on the Medicinal Plant Purslane <em>Portulaca oleracea</em>" with Elizabeth Botts, Coutney Brimmer, Tanner Miller, Kelley Summers and Dana Dudle.  Presented at the 52$^{nd}$ Annual Meeting of the Society for Economic Botany, July 9--13, 2011, St Louis Missouri. [Download](documents/SEB_2011_Poster.pdf)

"ChemoSpec: an R Package for the Chemometric Analysis of Spectroscopic Data" useR! 2010 Conference, National Institute of Standards and Technology, Gaithersburg Maryland, July 2010. [Download](documents/useR_2010_Poster.pdf)

"Assessing <em>Serenoa repens</em> (Arecaceae) Quality at the Retail Level Using Spectroscopic and Chemometric Methods" with Tao Ye and M. Daniel Raftery.  Presented at the 49$^{th}$ Annual Meeting of the Society for Economic Botany, June 1--5, 2008, Duke University. [Download](documents/SEB_2008_Poster.pdf)

## Miscellaneous

Google Summer of Code 2021: Mentored Tejasvi Gupta (India) who adapted [ChemoSpec](https://CRAN.R-project.org/package=ChemoSpec) to provide `ggplot2` and `plotly` graphics options.

Google Summer of Code 2021: Co-mentored Sang Truong (USA) who continued work on the [hyperSpec](https://github.com/r-hyperspec) package.

Google Summer of Code 2020: Co-mentored Erick Oduniyi (USA) who began the work of refactoring [hyperSpec](https://github.com/r-hyperspec) into sub-packages.

Google Summer of Code 2016: Co-mentored Anton Belov (Russia) in writing new functions for the [unmixR](https://gitlab.com/chemometrics/unmixR) package.

Google Summer of Code 2013: Co-mentored Conor McManus (Ireland) in writing the [unmixR](https://gitlab.com/chemometrics/unmixR) package.

I am a significant contributor to the [Valid NMR Chemometrics Wiki](http://www.validnmr.com/w/index.php?title=Chemometrics).

You can see my [StackExchange](https://stackexchange.com/users/316869/bryan-hanson?tab=accounts) Activity.
