---
title: "ChemoSpecUtils Update"
author: "Bryan Hanson"
date: 2020-04-27
tags: ["R", "ChemoSpecUtils"]
slug: "P13"
---

`ChemoSpecUtils`, a package that supports the common needs of [ChemoSpec](https://bryanhanson.github.io/ChemoSpec/) and [ChemoSpec2D](https://bryanhanson.github.io/ChemoSpec2D/), has been updated to fix an unfortunate distance calculation error in version 0.4.38, released in January of this year.  From the NEWS file for version 0.4.51:

* Function `rowDist`, which supports a number of functions, was overhauled to address confusion in the documentation, and in my head, about distances vs. similarities.  Also, different definitions found in the literature were documented more clearly.  The Minkowski distance option was removed (ask if you want it back), code was cleaned up, documentation greatly improved, an example was added and unit tests were added.  Plot scales were also corrected as necessary.  Depending upon which distance option is chosen, this change affects `hcaSpectra`, `plotSpectraDist`, `sampleDist` and `hcaScores` in package `ChemoSpec` as well as `hats_alignSpectra2D` and `hcaScores` in package `ChemoSpec2D`.

This brings to mind a Karl Broman quote I think about frequently:

> "Open source means everyone can see my stupid mistakes.
> Version control means everyone can see every stupid mistake I’ve ever made."
>
> -- <cite>Karl Broman</cite>

[Karl Broman quote source](https://kbroman.wordpress.com/2011/08/17/the-stupidest-r-code-ever/)
