---
title: "Simulating Spectroscopic Data Part 2"
author: "Bryan Hanson"
date: 2020-05-27
tags: ["R", "Simulated Data", "SpecHelpers", "Noise"]
slug: "P16"
draft: true
---

```{r hiddenSetup, echo = FALSE, eval = TRUE, results = "hide"}
rm(list = ls())
library("knitr")
opts_knit$set(echo = TRUE)
```

In the first [post](https://chemospec.org/2020/06/28/p15/) in this series, we showed how to vary the peak shape and add various baseline distortions when simulating spectroscopic data.  In this post we'll look at sources of noise and how to simulate noise.

# Sources of Noise

Before jumping into the practical aspects of simulating noise, let's survey some of the sources of noise in spectroscopic instrumentation.  After all, we need at least a rudimentary understanding of how noise arises in order to simulate it.  Full disclosure: I don't claim to be an expert on sources of noise.  I have enough experience to know some useful information and to know that there is so more to learn.  So please feel free to correct, elaborate or clarify anything you read here, via the comments.

To a large degree noise arises from instrument hardware and electronics, and as such will vary by the type of instrumentation.  I'll try to give a general overview with a few specific examples here and there.  _Do not_ take this as a comprehensive treatment of the topic!

## Noise Based on Counting Discrete Species

Any physical device that counts discrete species such as photons, electrons or other charged particles suffers from _shot noise_.  Examples include [CCD](https://en.wikipedia.org/wiki/Charge-coupled_device) detectors, [electron multipliers](https://en.wikipedia.org/wiki/Electron_multiplier) and [geiger counters](https://en.wikipedia.org/wiki/Geiger%E2%80%93M%C3%BCller_tube).  In addition, electronic devices that involve the storage or movement of charges (in other words, all of them) are also subject to shot noise.

So what is [shot noise](https://en.wikipedia.org/wiki/Shot_noise)?  It is noise that can be modeled by the [Poisson distribution](https://en.wikipedia.org/wiki/Poisson_distribution).  This distribution is used to describe discrete events that occur in a fixed interval of time[^1] and independently from each other.  Wikipedia uses the example of letters that arrive in the mail: The number of letters arriving on any given day is _independent_ of the number that arrived the day before or will arrive the day after.  And it's _discrete_: you can get one letter or two, never 1.5 letters.  For a spectroscopic example, consider a CCD device in the absence of any incident light.  The micro-meter capacitors that make up a CCD are subject to _thermal noise_ (see below) which means that even in the absence of incident light a small number of them can accidently "fire" and produce a signal (the _dark current_).  Even though thermal noise may be the origin of this signal, the device converts these signals into counts.  Thus the dark current represents counts and is shot noise that follows a Poisson distribution.

An important characteristic of the Poisson distribution is that it is sometimes referred to as the "law of rare events".  This is because when there are just a few events, the distribution is heavily skewed [left](https://en.wikipedia.org/wiki/Poisson_distribution#/media/File:Poisson_pmf.svg).  However, as the number of events increases, the Poisson distribution can be approximated by the Gaussian or normal distribution.[^2]  We'll see how that matters later.  Further, shot noise is independent of temperature or the frequency being monitored.  This distinguishes it from other types of noise.

Since all spectroscopic methods employ some kind of physical device as a detector, the net result is that shot noise is always present and is unavoidable in real, imperfect, physical devices.

## Noise Based on Thermal Agitation

[Thermal noise](https://en.wikipedia.org/wiki/Johnson%E2%80%93Nyquist_noise) arises from the intrinsic motion of atoms, which is temperature dependent.  It occurs in all electronic circuits, and is frequency and voltage independent.  Because it is ultimately related to motion, cooling detectors reduces the thermal noise of the signal.


## Noise Based on Mechanical Motion

## Relative Contribution of Noise Sources

## Meta-Noise

## Artifacts

stray light
cosmic raws
how to simulate

# Simulation of Noise


vibration
effect of signal averaging
simulation of stray light cosmic rays

  Some instruments, like NMR, use antennas as their detectors, and the signal is sent to analog-to-digital converters (ADC).  I don't know how these work on a physical level, and the result is a digital signal to be detected at a certain level rather than formal counting. Conceptually however, the output is discrete (i.e. digitized) and it would logically have an analog to the dark current.


https://chemistry.stackexchange.com/questions/96064/is-there-a-real-detection-limit-in-nmr-spectroscopy

 [^1]: Or space.
 [^2]: The Poisson distribution is a discrete distribution.  Technically, for a large number of events, the Poisson converges to the Binomial distribution, another discrete distribution.  In either case however, the Gaussian distribution, which is a continuous distribution, is a good substitute.
