---
title: "DIY NMR in  Earth's Field"
description: "A super simple design"
date: "2023-06-12"
categories: [NMR, EF-NMR, NQR, DIY]
format:
  html
bibliography: references.bib
draft: false
---

I have always loved every aspect of NMR.  My first introduction was as an undergraduate at Cal State Los Angeles, where I was introduced to a Bruker instrument that used a folded punched tape to read in its operating system.  Fortunately, that machine was already quite older and there was a Varian EM-360 which was the work horse for routine spectra (bonus points if you can guess roughly what year this was!).  Besides the extremely broad usefulness of NMR instruments, the combination of physics, chemistry, computer science and electronics that undergird the practical aspects of NMR are endlessly fascinating to me.

The development of simple, home-built NMR instruments over the past two decades is very interesting and appealing.  These instruments typically don't have a magnet, but rather use the earth's magnetic field and some type of polarization process to improve sensitivity. Most of these instruments use an inexpensive microprocessor like an Arduino or Raspberry Pi to control the instrument, along with some purpose-built electronic circuits.  Good examples are the work of Michal (@Michal2010, @Michal2020), Trevelyan (@Trevelyan) and Bryden (@Bryden2021).  These instruments of course aren't able to give the same results as higher-field instruments with superconducting magnets or Halbach arrays.  What can you do with these instruments?  Because earth's magnetic field is very homogeneous locally, the line widths are very narrow, and thus coupling constants and $T_2$ can be measured.[^1] However, the chemical shift range is really small, so structural studies are out.  Sensitivity is relatively poor as well.  Imaging (MRI) is in principle possible.  By the way, there are also examples of DIY Nuclear Quadropole Resonce (NQR) instruments as well, which require no magnetic field (@Hiblot2008).

Recently, a simpler DIY NMR instrument was published as a [Hackaday](https://hackaday.io/) project by Andy Nichol.  This ["Nuclear Magnetic Resonance for Everybody"](https://hackaday.io/project/191192-nuclear-magnetic-resonance-for-everyone) project is unique due to its use of only off-the-shelf commericially available hardware components.  Because the hydrogen Larmor precession frequency in earth's magnetic field is in the audio range, the project uses a standard and readily available audio amplifier to simplify the signal detection process.  In addition, the complexities of pulse programming are avoided in this project by using a mechanical switch to switch between polarization and detection modes.  Finally, a single coil is employed for both polarization and detection.  Signal processing is handled by readily available software.

This is an interesting project and it is the most basic entry point into DIY NMR that I have encountered. If it whets your appetite, the project can be made progressively more sophisticated by selectively bringing in the more advanced features of some of the other designs.

[^1]: Locally homogeneous provided you are away from buildings, electrical transmission lines etc.
